server:
    port: 9000
    contextPath: /travel
logging:
  level:
    org:
      springframework:
        security: INFO

  file: travelapi.log
  path: logs/
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'   